Do not overwrite role in install phase
This causes an exception later:

 undefined method `[]' for nil:NilClass
 /opt/dell/crowbar_framework/app/models/provisioner_service.rb:158